# git-cliff ~ default configuration file
# https://git-cliff.org/docs/configuration
#
# Lines starting with "#" are comments.
# Configuration options are organized into tables and keys.
# See documentation for more information on available options.

[changelog]
# changelog header
header = """
# Changelog\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        {% set first_line = commit.message | split(pat="\n") | first %}
        {% set rest_message = commit.message | split(pat="\n") | slice(start=1) | join(sep="\n") %}
        {% set author_username = commit.author.name | replace(from=" ", to="") %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**Breaking**] {% endif %}\
            {{ first_line | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](REPO_URL/commit/{{ commit.id }})) \
            {% if commit.remote.username %} @{{ commit.remote.username }}{% else %} @{{ author_username }}{% endif %}

            {{ rest_message }}
    {% endfor %}
{% endfor %}\n
"""
# template for the changelog footer
footer = """
"""
# remove the leading and trailing s
trim = true
# postprocessors
postprocessors = [
  { pattern = "REPO_URL", replace = "https://github.com/lynx-family/serval-kit" }
]

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = false
# filter out the commits that are not conventional
filter_unconventional = false
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
  { pattern = "(?m)^.*changelog: yes.*\n?", replace = "" },
  { pattern = "(?m)^.*issue:.*\n?", replace = "" },
  { pattern = "(?m)^.*doc:.*\n?", replace = "" },
  { pattern = "(?m)^.*TEST:.*\n?", replace = "" },
  { pattern = "(?m)^.*AutoLand:.*\n?", replace = "" },
  { pattern = "(?m)^.*AutoSubmit:.*\n?", replace = "" },
  { pattern = "(?m)^.*SkipChecks:.*\n?", replace = "" },
  { pattern = "(?m)^.*ExternalPullRequestID:.*\n?", replace = "" },
  { pattern = "(?m)^.*ExternalGitURL:.*\n?", replace = "" },
  { pattern = "(?m)^.*Change-Id:.*\n?", replace = "" },
  { pattern = "(?m)^.*Signed-off-by:.*\n?", replace = "" },
  { pattern = "(?m)^#.*\n?", replace = "" },
  { pattern = "\n", replace = "\n\t"}
]

# regex for parsing and grouping commits
commit_parsers = [
  { message = ".*changelog: no.*", skip = true },
  { message = "^\\[Breaking\\]", group = "<!-- 0 -->ğŸ’¥ Breaking Changes" },
  { message = "^\\[Feature\\]", group = "<!-- 1 -->âœ¨ Features" },
  { message = "^\\[BugFix\\]", group = "<!-- 2 -->ğŸ› Bug Fixes" },
  { message = "^\\[Refactor\\]", group = "<!-- 3 -->ğŸšœ Refactor" },
  { message = "^\\[Optimize\\]", group = "<!-- 4 -->ğŸš€ Optimization" },
  { message = "^\\[Doc\\]", group = "<!-- 5 -->ğŸ“š Documentation" },
  { message = "^\\[Performance\\]", group = "<!-- 6 -->âš¡ Performance" },
  { message = "^style", group = "<!-- 7 -->ğŸ¨ Styling" },
  { message = "^\\[Testing\\]", group = "<!-- 8 -->ğŸ§ª Testing" },
  { message = "^\\[Infra\\]", group = "<!-- 9 -->ğŸ› ï¸ Infra" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore|^ci", group = "<!-- 9 -->âš™ï¸ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 10 -->ğŸ›¡ï¸ Security" },
  { message = "^Revert", skip = true },
]

# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# regex for matching git tags
# tag_pattern = "(A_|platformios).*"
# regex for skipping tags
# skip_tags = ""
# regex for ignoring tags
ignore_tags = ".*(alpha).*"
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# limit the number of commits included in the changelog.
# limit_commits = 42
