[git]
conventional_commits = false
filter_commits = true
commit_parsers = [
  { message = ".*changelog: no.*", skip = true },

  { message = ".*", group = "General" }
]

[changelog]
header = """
## <!-- version -->
"""

body = """
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/lynx-family/serval-kit/commit/{{ commit.id }}))
{% endfor %}
"""